#####
#  GitHub Pages / Jekyll settings / config

headers:
  title:     Slide Show (S9)
  subtitle:  "Write Your Talks in Plain Text w/ Markdown"
  author:    Gerald Bauer et al
  generator: GitHub Pages w/ Jekyll

collections:
  slides:
    output: false


exclude:
- README.md
- NOTES.md
- package.json
- g5.txt
- io2011
